spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm-service?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
application:
  default-user:
    email: admin@localhost
    password: admin
  aws:
    bucket: crm
    region: eu-west-1
