spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
application:
  default-user:
    email: admin@localhost
    password: admin
  aws:
    bucket: crm
    region: eu-west-1
